// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Models;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250421164009_AddOfertaDoacao")]
    partial class AddOfertaDoacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("app.Models.ItemOferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Alimento")
                        .HasColumnType("int");

                    b.Property<int>("IdOferta")
                        .HasColumnType("int");

                    b.Property<int>("MedidaItem")
                        .HasColumnType("int");

                    b.Property<int>("QtdeItem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdOferta");

                    b.ToTable("ItemOferta");
                });

            modelBuilder.Entity("app.Models.OfertaDoacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAgendada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuarioDoador")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioOng")
                        .HasColumnType("int");

                    b.Property<bool>("IsCestaCompleta")
                        .HasColumnType("bit");

                    b.Property<int>("QtdeCestas")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoTransporte")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioDoador");

                    b.HasIndex("IdUsuarioOng");

                    b.ToTable("OfertaDoacao");
                });

            modelBuilder.Entity("app.Models.OpcaoAgendamentoOferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaDaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HorarioFinal")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdOferta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdOferta");

                    b.ToTable("OpcaoAgendamentoOferta");
                });

            modelBuilder.Entity("app.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefone")
                        .HasColumnType("int");

                    b.Property<string>("TipoDeUsuario")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoDeUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("app.Models.UsuarioDoadorPf", b =>
                {
                    b.HasBaseType("app.Models.Usuario");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.HasDiscriminator().HasValue("UsuarioDoadorPf");
                });

            modelBuilder.Entity("app.Models.UsuarioDoadorPj", b =>
                {
                    b.HasBaseType("app.Models.Usuario");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cnpj");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RazaoSocial");

                    b.HasDiscriminator().HasValue("UsuarioDoadorPj");
                });

            modelBuilder.Entity("app.Models.UsuarioOng", b =>
                {
                    b.HasBaseType("app.Models.Usuario");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cnpj");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RazaoSocial");

                    b.HasDiscriminator().HasValue("UsuarioOng");
                });

            modelBuilder.Entity("app.Models.ItemOferta", b =>
                {
                    b.HasOne("app.Models.OfertaDoacao", "Oferta")
                        .WithMany("ItensOferta")
                        .HasForeignKey("IdOferta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("app.Models.OfertaDoacao", b =>
                {
                    b.HasOne("app.Models.Usuario", "UsuarioDoador")
                        .WithMany("OfertasFeitas")
                        .HasForeignKey("IdUsuarioDoador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("app.Models.Usuario", "UsuarioOng")
                        .WithMany("OfertasRecebidas")
                        .HasForeignKey("IdUsuarioOng")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioDoador");

                    b.Navigation("UsuarioOng");
                });

            modelBuilder.Entity("app.Models.OpcaoAgendamentoOferta", b =>
                {
                    b.HasOne("app.Models.OfertaDoacao", "Oferta")
                        .WithMany("OpcoesAgendamento")
                        .HasForeignKey("IdOferta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("app.Models.OfertaDoacao", b =>
                {
                    b.Navigation("ItensOferta");

                    b.Navigation("OpcoesAgendamento");
                });

            modelBuilder.Entity("app.Models.Usuario", b =>
                {
                    b.Navigation("OfertasFeitas");

                    b.Navigation("OfertasRecebidas");
                });
#pragma warning restore 612, 618
        }
    }
}
